<?php
    DEFINE("NO_RESULTS_FOR_THIS_SEARCH", 0);
    DEFINE("SUCCESSUFUL_SEARCH", 1);
    DEFINE("INVALID_PARAMETERS_IN_SEARCH", 2);
    DEFINE("INVALID_NAME_IN_SEARCH", 3);
    DEFINE("INVALID_ID_IN_SEARCH", 4);
    DEFINE("ERROR_IN_SEARCH", 5);
    

